# Generated by Django 3.0.6 on 2022-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20220829_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_noticias'),
        ),
    ]
