# Generated by Django 3.0.6 on 2022-08-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descargas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Archivo',
        ),
    ]
