# Generated by Django 3.0.6 on 2022-08-29 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('descargas', '0002_auto_20220829_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='author',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
